app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

partner_registration:
    pattern: /register/partner
    defaults: { _controller: AppBundle:RegistrationPartner:register }

customer_registration:
    pattern: /register/customer
    defaults: { _controller: AppBundle:RegistrationCustomer:register }

